import type { AiArchitectService } from "../ports/ai-architect-service";
import type { GitHubRepository } from "../ports/github-repository";
import type { NotionRepository } from "../ports/notion-repository";

export interface WorkflowRunSummary {
  processedIdeas: number;
  createdProjects: number;
  createdTasks: number;
  createdIssues: number;
}

export class IdeaToProjectWorkflow {
  constructor(
    private readonly notionRepository: NotionRepository,
    private readonly aiArchitectService: AiArchitectService,
    private readonly githubRepository: GitHubRepository,
  ) {}

  async runOnce(): Promise<WorkflowRunSummary> {
    const ideas = await this.notionRepository.listNewIdeas();
    console.log(`Found ${ideas.length} new idea(s) to process.`);

    const summary: WorkflowRunSummary = {
      processedIdeas: 0,
      createdProjects: 0,
      createdTasks: 0,
      createdIssues: 0,
    };

    for (const idea of ideas) {
      console.log(`Processing idea ${idea.id}: ${idea.title}`);

      const generatedProject =
        await this.aiArchitectService.generateProjectFromIdea(idea.title);

      const project = await this.notionRepository.createProject({
        ideaId: idea.id,
        name: generatedProject.product_overview.name,
        productPlan: generatedProject.product_overview.description,
        architecture: JSON.stringify(generatedProject.architecture, null, 2),
      });

      const createdTasks = await this.notionRepository.createTasks({
        projectId: project.id,
        tasks: generatedProject.tasks.map((task) => ({
          title: task.title,
          description: task.description,
          priority: task.priority,
        })),
      });

      for (const task of createdTasks) {
        await this.githubRepository.createIssue({
          title: buildIssueTitle(project.name, task.title),
          body: buildIssueBody({
            ideaId: idea.id,
            projectName: project.name,
            taskId: task.id,
            taskTitle: task.title,
            taskDescription: task.description,
            priority: task.priority,
          }),
          labels: buildIssueLabels(task.priority),
        });
        summary.createdIssues += 1;
      }

      summary.processedIdeas += 1;
      summary.createdProjects += 1;
      summary.createdTasks += createdTasks.length;
    }

    console.log(
      `Workflow summary: ideas=${summary.processedIdeas}, projects=${summary.createdProjects}, tasks=${summary.createdTasks}, issues=${summary.createdIssues}`,
    );

    return summary;
  }
}

interface IssueTemplateInput {
  ideaId: string;
  projectName: string;
  taskId: string;
  taskTitle: string;
  taskDescription: string;
  priority: "low" | "medium" | "high";
}

const buildIssueTitle = (projectName: string, taskTitle: string): string => {
  const cleanProjectName = normalizeText(projectName);
  const cleanTaskTitle = normalizeText(taskTitle);
  const rawTitle = `[${cleanProjectName}] ${cleanTaskTitle}`;

  if (rawTitle.length <= 90) {
    return rawTitle;
  }

  return `${rawTitle.slice(0, 87).trimEnd()}...`;
};

const buildIssueBody = (input: IssueTemplateInput): string =>
  `## Summary
${normalizeText(input.taskTitle)}

## Context
- Project: ${normalizeText(input.projectName)}
- Source Idea ID: ${input.ideaId}
- Source Task ID: ${input.taskId}
- Priority: ${input.priority}
- Generated by: Notion AI Architect

## Task Description
${normalizeText(input.taskDescription)}

## Acceptance Criteria
- [ ] Implementation completed
- [ ] Tests added or updated
- [ ] Documentation updated if needed`;

const buildIssueLabels = (
  priority: "low" | "medium" | "high",
): ReadonlyArray<string> => [
  "ai-generated",
  "demo",
  "source:notion",
  `priority:${priority}`,
];

const normalizeText = (value: string): string => value.replace(/\s+/g, " ").trim();
